name:                blog-engine
version:             0.1.0.0
github:              "pois0/BlogEngine"
license:             Apache-2.0
author:              "pois"
maintainer:          "dev@pois.jp"
copyright:           "2020 pois"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pois0/BlogEngine#readme>

dependencies:
- base >= 4.13.0 && < 5
- extra >= 1.7.8
- relude >= 0.7.0.0
- pandoc >= 2.10.1
- yaml >= 0.11.5.0
- text >= 1.2.4.0
- time >= 1.9.3
- directory >= 1.3.6.0
- split >= 0.2.3.4
- shakespeare >= 2.0.25
- blaze-html >= 0.9.1.1
- filepath >= 1.4.2.1
- async >= 2.2.2
- data-default >= 0.7.1.1

library:
  source-dirs: src

executables:
  blog-engine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - blog-engine

tests:
  blog-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-engine
